### PR TITLE
Automated tests, library loader changes, documentation

### PR DESCRIPTION
**Pull request by mattgwwalker**
Hi Zuzu-Typ,

I gave up :o/  Here is everything.  In one mighty pull request.  I've been trying to backport things from my version to yours, but it all just got too hairy.

This pull request contains:
- All the automated tests.  Overall we have about 75% coverage with these 39 tests.  However, there is almost 100% coverage of the Opus-related API.  As a consequence, you can ignore my previous pull request (#37) as it is now outdated.
- All the documentation, which also includes a discussion of PyOgg development, which includes automated testing and building of the documentation.  As a consequence, you can ignore my previous pull request (#36) as it too is outdated.
- Library loader changes.  These were discussed in issue #32.  They are a step towards a wheel for macOS.
- A considerable number of bug fixes or extra features to probably all the Opus-related classes; notably OggOpusWriter is now directly subclassed from OpusBufferedEncoder, thus making it much easier to use.
- Fixes of the examples to bring them up-to-date with the current API.

Sorry this is so massive.  However with the newly-added automated tests at least you can demonstrate that the code works ;o)

Cheers,

Matthew

### CODE REVIEW

**Comment by mattgwwalker** [comment]
Hi again Zuzu-Typ,

I've added to this pull request macOS wheels:
- There is now a directory pyogg/libs with all the shared libraries for macOS, Windows 32-bit, and Windows 64-bit.  The appropriate shared libraries are copied into the wheel by the build process.
- I have also added to the documentation an explanation of how wheels can be built.
- I have tested this on Mac and Windows.

If you have any questions, please fire away.  We can update the documentation if there are any issues that aren't clear.

Cheers,

Matthew

**Comment by Zuzu-Typ** [comment]
Hi there Matthew, 

I'm sorry that I didn't have a look at this earlier. It's amazing how much work you put into the library.
Frankly, I don't currently have enough time to keep up and I really don't want your work to be wasted, so I would like to ask you if you'd like to become a collaborator of this project (here and on [PyPI](pypi.org)). If you'd prefer I could also transfer ownership of this repository to you, because I feel like you've done more work for it than I did already.

Please do tell me what you think about it.

Cheers
--Zuzu_Typ--

**Comment by mattgwwalker** [comment]
Hi Zuzu-Typ,

I'd be very happy to be added in as a collaborator.  Thanks for asking me.

The project I'm currently working on calls your library at least once every 20ms for hours on end, so I've been very engaged with PyOgg because of it.  As a contributor, here are the things I'd like to set up for the PyOgg GitHub repository:

- Continuous Integration using Travis (which is free for open source projects) based on the automated testing that's in this pull request
- Continuous Documentation using Read The Docs based on the documentation that is in this pull request.

I'd also like it if we did a PyPi release as I think there are a number of newly-added features that developers would find useful.

I was in your position with [another project I started](https://github.com/mattgwwalker/msg-extractor) and I was very pleased to see the community of developers form around it.  It was only a good thing for that project as, just like you, I didn't have time to work on it.  However, I also feel it's your baby, and ownership of the project is best left with you.

Cheers,

Matthew

**Comment by Zuzu-Typ** [comment]
Hi there Matthew,

I'm glad that you decided to join (: 

I thought about adding CI to PyOgg, but in my opinion it would only make sense if the binaries for ogg, vorbis, opus, flac, etc. would also be built. Unfortunately most of those libraries don't really work well together and require quite a bit of tweaking to get them to build. That's why I decided not to add CI.
Of course, using pre-generated libraries would also be fine, but since I didn't have tests at the time, there was no real reason to incorporate CI.

I haven't used ReadTheDocs before, but it does sound like a good idea.
The only thing I dislike about it is that it uses reStructuredText.. I know you can also use markdown, but I'm not sure if I would consider that to be much better. I find most markup languages cumbersome to write, especially when things are automatically formatted. I've considered creating a parser that's able to convert from different markup languages to HTML and back, because there are much better editors out there for HTML. Anyway, unrelated.

Do you have a PyPI account by any chance?
Because I could add you as a collaborator there too.

Cheers,
--Zuzu_Typ--

**Comment by mattgwwalker** [comment]
Hi again,

I've accepted the collaboration invitation.  Would you like me to merge this pull request myself, or would you prefer to do it?

On the subject of the binaries, this pull request includes pre-built binaries for Windows 32-bit, Windows 64-bit and macOS 64-bit.  I agree that automating the build process for all the required libraries would be ideal, but the amount of work required would be very large.  Using the pre-built binaries will be satisfactory, if not ideal.  Combining the pre-built libraries with the automated tests in this pull request would allow us to implement continuous integration.  Would you like me to look into this?  I can't make it my top priority but I'd consider it interesting to tick off and it would make future development more reliable.

The documentation I have included in this pull request uses Sphinx with restructured text.  It's not the most fun of markup languages, I agree, but from now on, we can just copy markup from what has already been written.  Would you like me to look into hooking us into ReadTheDocs?

As for PyPi, my username there is mattgwwalker.

Cheers,

Matthew

**Comment by Zuzu-Typ** [comment]
Hey Matthew,

We're kinda abusing this PR as a means of communication, aren't we 😅
Anyway, if you want to, you can merge this PR yourself.

I can try setting up CI, as I've done it before, but it has been a while and it might take a few tries to get right.
We can set up CI to automatically upload the releases so we don't have to do that manually.

I'm not sure wether or not it would also be possible to generate the docs via CI and upload them to ReadTheDocs.io or wheresoever the documentation would be hosted, as I haven't looked into it yet, but do feel free to try setting it up. We can look into "continuous documentation" later (: 

Again, thank you for your time and effort!

Cheers,
--Zuzu_Typ--

**Pull request merged**
